ft-buyer-signup #3
atlp-rwanda/ecommerce-app-champions-bn pull request #12
Opened 2023-03-08 17:00 UTC by patsicko

# What this PR do
 - Create user model
- Create user migration
- Create buyer controller
- Create buyer api endpoint
- Test api on postman 
# Description of the task
- A buyer is able to signup with email and password
## How should this be manually tested
- open postman
- set your HTTP request to POST
- input API endpoint
- switch to the Body tab
- Click raw
- select JSON
-  create a json object with firstName, lastName,email,password
- Click Send.
- Status: 201 ok should be displayed
- Updated data are showing up in the body.

## Trello story id
#003

2023-03-09 15:05 UTC, sostene12 reviewed
you can add more details on this pull, like profile model and work hand in hand with task of aimable

2023-03-10 07:47 UTC, sostene12 reviewed
- please solve the conflicts

2023-03-14 18:41 UTC, sostene12 approved these changes

2023-03-15 07:48 UTC, wakaflorien requested changes
- **TEST_DB_HOST, TEST_DB_USERNAME, TEST_DB_PASSWORD** are not needed.
- existing on conflict error codes should be 409
- no need to push console logs in your codes once they served your purpose
- profile model still unnormalized e.g how is **businessNumber** attribute relevant to **buyer**. same goes to **businessAddress**, **taxIdNumber, typeOfProducts**
- the PR description doesn't well guide to how this can be manually tested

2023-03-15 08:27 UTC, chrill-christella approved these changes

2023-03-16 07:20 UTC, wakaflorien requested changes

2023-03-16 07:20 UTC, wakaflorien commented on src/controllers/buyerController.js
> +    const token = jwt.sign({ id: buyer.id }, process.env.JWT_SECRET, {
- when the JWT_SECRET is no found the account is still created.

2023-03-16 07:20 UTC, wakaflorien commented on test/user.test.js
> + console.log(response.body);
- no need of leaving this console logs

2023-03-16 07:41 UTC, wakaflorien approved these changes

2023-03-16 07:42 UTC, merged