#8 Ft update profile
atlp-rwanda/ecommerce-app-champions-bn pull request #18
Opened 2023-03-14 10:41 UTC by chrill-christella

### what does this PR do?

update the profile of the user

### Description of the task to be completed

- generate the user profile whenever a user sign up or login 
- create user profile controller and route to update the profile of a buyer or a sender
- add necessary validations

2023-03-16 14:46 UTC, sostene12 requested changes
please consider the conflicts you are having, it would help if you solve them first and then rebase the base branch (develop)

2023-03-19 04:56 UTC, patsicko requested changes
- We are normalizing user model by creating user profiles with respect to their respective roles.
I can suggest you to rebase ft: roles permissions #20 to have the latest changes. It will help.
- CI.yml has been changed to run a script that undo all migrations after each test. The same changes have been applied to the test script in package.json.  Hopefully this will solve the issues of your tests that are not passing.

2023-03-21 11:55 UTC, Shumba250 approved these changes

2023-03-22 07:19 UTC, Luciefifi approved these changes

2023-03-22 08:48 UTC, sostene12 requested changes

2023-03-22 08:48 UTC, sostene12 commented on src/api-docs/buyer.docs.js
you are sending the id of user, hence you are finding by email from req.body

```
static async getProfile (req, res, next) {
  try {
    const { userId } = req.params;
    const {dataValues} = await user.findOne({where:{email:req.body.email}});
    const profile = await profiles.findUserProfile(userId);
    const {...others}= dataValues;
    if (profile) {
      res.json({ message: req.t('Found'), data: {others,profile} });
    } else {

      const Message = req.t('notfound');
      res.json({ message: Message });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
    next(error);
  }
```

2023-03-22 08:48 UTC, sostene12 commented on src/routes/buyer.route.js
it can be good , if before updating you must login first

2023-03-22 08:49 UTC, sostene12 commented
also, solve conflicts, and apply the comments on the vendor aswell

2023-03-22 17:38 UTC, chrill-christella commented on src/routes/buyer.route.js
resolved this issue too

2023-03-22 20:02 UTC, wakaflorien approved these changes

2023-03-22 20:04 UTC, merged