Ft logout
atlp-rwanda/ecommerce-app-champions-bn pull request #19
Opened 2023-03-15 18:56 UTC by oliviertech212

## what does this PR do:
Logout from the App
## Description
- implement logout to authenticated user
- implement middleware to access some protected route
- document route with swagger
##  To test this 
- clone repo
- change branch by `git checkout ft-logout`
- run `npm install`
- create `.env` file and look at `.env.example`
- run migrations `npm run migrate:up`
- run `npm run db:seeds`
- to start server run `npm run dev` also you can use `npm run test` to run test
- once you start server at given port  `http://localhost:`
- open your browser to start test endpoint with swagger  `http://localhost:{PORT}/docs`.  then to test logout first test login once user loged in token will be save in cookies 
- after teting logout token will be deleted from cookies  
- also you can use this url `http://localhost:{PORT}/api/vendor/logout`
## Card Number #6

2023-03-20 11:45 UTC, Shumba250 requested changes
npm run migrate:up is not working and also rebase to develop to fix the conflicts

2023-03-21 21:31 UTC, patsicko approved these changes

2023-03-22 06:51 UTC, chrill-christella approved these changes

2023-03-22 08:19 UTC, wakaflorien approved these changes

2023-03-22 08:33 UTC, Shumba250 approved these changes

2023-03-22 08:34 UTC, merged