ft: roles permissions
atlp-rwanda/ecommerce-app-champions-bn pull request #20
Opened 2023-03-17 07:05 UTC by sostene12

#### What does this PR do?
-  implement roles and permissions
#### Description of Task to be completed
- implement create permissions
- implement create roles
- implement assign role and permissions to the user being created
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ft-roles-permissions
- create a .env file and put the required environment variables from .env.example file
- run in the terminal `npm run migrate:up`,
- make a post request `http://localhost:5000/api/permission/create` to create permission
- make a post request `http://localhost:5000/api/role/create` to create role
- make a post request `http://localhost:5000/api/vendor/signup` to create a user  , the roles and permissions are automatically assigned
- to check the roles and permissions assigned to the user `http://localhost:5000/api/vendor/{id}`
#### What are the relevant pivotal tracker stories?
-Create Roles and Set Permissions `card #12`

2023-03-18 19:40 UTC, patsicko requested changes
Make sure that you have an updated ci.yml. 
Consider deleting all migrations after runing tests. It will help

2023-03-18 21:09 UTC, sostene12 commented
> Make sure that you have an updated ci.yml. Consider deleting all migrations after runing tests. It will help

i dit implement it

2023-03-19 04:42 UTC, patsicko approved these changes

2023-03-19 16:47 UTC, chrill-christella approved these changes

2023-03-21 10:46 UTC, wakaflorien approved these changes

2023-03-21 10:46 UTC, merged