ft-list-items
atlp-rwanda/ecommerce-app-champions-bn pull request #24
Opened 2023-03-22 11:20 UTC by patsicko

# What this PR do
# List all items in collection
# Description of the task
- Create product model
- Create product migrations
## How should this be manually tested
- clone the repo
- use npm install to install all packages
- Add all required environment variables following the .env.example provided
- use npx sequelize db:migrate to migrate migrations
- use npm run dev to start the server
use the appropriate router in postman or thunderclient 
navigate to  the http://localhost:PORT  by replacing 'PORT' the port that your the app is listening to, and test it using the documented API. By sending a request to create a buyer, the response will be displayed containging a newly created buyer and welcome message will be sent to the provided email
- Run:   npm run migrate:up
- Tables will be created in database

2023-03-22 11:21 UTC, patsicko commented
![](https://github.trello.services/images/mini-trello-icon.png) [A user should be able to list all items](https://trello.com/c/fhatu25F/21-a-user-should-be-able-to-list-all-items)

2023-03-27 08:13 UTC, wakaflorien commented
**Make a meaningfull PR description**

![image](https://user-images.githubusercontent.com/48131185/227881223-fc564083-7d76-41f6-8dcd-8e9e4eacb706.png)

2023-03-27 09:32 UTC, wakaflorien commented on test/product.test.js
> +  describe("testing get all items",() =>{
- add more testcases.

2023-03-27 09:32 UTC, wakaflorien requested changes
- Correct and improve failing tests

2023-03-27 10:10 UTC, sostene12 reviewed
i'm having troubles in running creating products,

2023-03-27 13:28 UTC, wakaflorien approved these changes

2023-03-27 14:45 UTC, oliviertech212 approved these changes

2023-03-27 14:47 UTC, wakaflorien approved these changes

2023-03-27 14:48 UTC, merged