#23 Build REST API for buyer wishlist
atlp-rwanda/ecommerce-app-champions-bn pull request #26
Opened 2023-03-23 14:45 UTC by Luciefifi

# What does this PR do 
allow buyers to add and view the product on their wishlist

# Description of the task to be completed
.  Add item to the buyer's wishlist
.The product details (name, price, image) should be retrieved from the database
.The updated wishlist should be stored in the buyer's account
.A confirmation message should be sent to the frontend to be displayed to the buyer

# How should this be manually tested 
. clone this repository
. open it in your favorite editor
.cd into it
. checkout to `ft-buyer-wishlist`
.run migrations and seeds  by `npm run migrate:up` and `npm run db:seeds` respectively in your terminal
. start the server by running `npm run dev`
. make a post request in postman `http://localhost:${port}/api/product/addToWishlist/{productId}` to add product to a wishlist
.make a get request in postman `http://localhost:${port}/api/product/reviewWishlistItems/` to view your wishlist
.You may also use the documented api by running your server and the in your browser  `http://localhost:${port}/docs`

# Relevant pivotal tracker user story
#23

2023-03-28 19:57 UTC, sostene12 requested changes
the endpoints are working, but the tests are failing

2023-03-29 04:13 UTC, Luciefifi commented
> the endpoints are working, but the tests are failing

I worked on them , They are now passing

2023-03-29 04:43 UTC, patsicko approved these changes

2023-03-29 05:35 UTC, chrill-christella approved these changes

2023-03-29 06:11 UTC, nicele08 requested changes
Hi @Luciefifi,

Thank you for submitting this pull request! I've had a chance to review the code and I must say, you've done a great job. The code is well-organized, easy to read, and the REST API endpoints are implemented correctly.

I do have a few suggestions that I believe could make the code even better. I've provided my feedback on the pull request, so please take a look and let me know if you have any questions or if you would like further feedback.

Keep up the great work!

2023-03-29 06:11 UTC, nicele08 commented on src/controllers/productController.js
> +      console.log(req.user)
This console.log statements are included for debugging purposes only and should be removed or commented out in production code.

2023-03-29 06:11 UTC, nicele08 commented on src/controllers/productController.js
> +        wishlists = newWishlist;
The `await Wishlist.create()` method creates a new Wishlist object and saves it to the database automatically. Therefore, calling `newWishlist.save()` is redundant and does not have any effect on the functionality of the code.

2023-03-29 06:11 UTC, nicele08 commented on src/controllers/productController.js
> +}
I like this logic but there are a few optimizations that can be made to improve its performance and readability.
Use `Promise.all()`: Instead of making one database call for each product in the wishlist, it's more efficient to make all the calls concurrently using `Promise.all()`.
example: 
`
const productIds = wishlistItems.products;
const productPromises = productIds.map((productId) => {
  return Product.findOne({ where: { productId: productId } });
});

const products = await Promise.all(productPromises);
`

2023-03-29 06:11 UTC, nicele08 commented on src/controllers/productController.js
> +      return res.status(500).json({ error: error.message });
In this error handling block improve and provide more information by including a message field in the response, this code block provides more informative error messages to the client.
Example:
`
return res.status(500).json({ 
     error: error.message,
     message: error.name === 'SequelizeValidationError' ? error.message : 'Internal server error'
});
`

2023-03-29 06:11 UTC, nicele08 commented on src/controllers/productController.js
> +res.json({wishlist:products})
You forgot to mention status code on this response

2023-03-29 06:11 UTC, nicele08 commented on src/controllers/productController.js
> +}
Wrap the entire function in a try-catch block to handle any errors that may occur during the database calls. If an error occurs, the code catches the error, logs it to the console using console.error(), and returns a 500 Internal Server Error status code with a generic error message.

By adding a try-catch block, the code becomes more robust and handles errors gracefully, ensuring that the server does not crash or expose sensitive information to the client.

2023-03-29 06:11 UTC, nicele08 commented on src/controllers/productController.js
> +
Remove this empty lines.

2023-03-29 06:11 UTC, nicele08 commented on src/middlewares/authenticate.js
> +      console.log(req.user.role.roleName)
The console.log() statement is only for debugging purposes and should be removed from production code.

2023-03-29 06:11 UTC, nicele08 commented on src/middlewares/authenticate.js
> +          .json({ status: "error", error: "you are not authorized b" });
The error message "you are not authorized b" in the response is not very informative and does not provide any details about the error.

2023-03-29 06:11 UTC, nicele08 commented on src/middlewares/authenticate.js
> +          .status(401)
The 401 Unauthorized status code is appropriate for authentication errors, but it might be more appropriate to use a 403 Forbidden status code for authorization errors.

2023-03-29 06:11 UTC, nicele08 commented on src/routes/product.route.js
> +
Remove these empty lines.

2023-03-29 06:11 UTC, nicele08 commented on test/buyer.test.js
> +
you could use the `beforeAll ` hook in Jest to obtain a token before running all tests:
example:
`
beforeAll(async () => {
  const res = await request.post("/api/user/login").send({
    email: "ngarukiyimanasostene@gmail.com",
    password: "1234567@password"
  });
  token = res.body.token;
});
`
the `beforeAll` hook runs once before all tests, and sends a login request to the server to obtain a token. The token is then assigned to the token variable, which is used in subsequent requests using the `set `method on the `request `object to add the token to the request headers.

2023-03-29 06:22 UTC, sostene12 approved these changes

2023-03-29 08:01 UTC, Shumba250 approved these changes

2023-03-29 09:05 UTC, wakaflorien requested changes

2023-03-29 09:05 UTC, wakaflorien commented on src/controllers/productController.js
> +        return res.status(400).json({ message: "Product already in wishlist" });
- here to follow response example share by @nicele08

2023-03-29 09:05 UTC, wakaflorien commented on src/controllers/productController.js
> +  console.log(product)
- remember to remove this console log here too.

2023-03-29 09:05 UTC, wakaflorien commented on src/controllers/resetPasswordController.js
>      console.log(err);
- again let's ommit console logs on production codes.

2023-03-29 09:05 UTC, wakaflorien commented on test/product.test.js
- you can remove these blank lines

2023-03-29 13:28 UTC, Luciefifi commented
> Hi @Luciefifi,
> 
> Thank you for submitting this pull request! I've had a chance to review the code and I must say, you've done a great job. The code is well-organized, easy to read, and the REST API endpoints are implemented correctly.
> 
> I do have a few suggestions that I believe could make the code even better. I've provided my feedback on the pull request, so please take a look and let me know if you have any questions or if you would like further feedback.
> 
> Keep up the great work!

Hi@nicele08
Pleasure is mine , and thank you so much 🙏 for your suggestions

2023-03-29 15:25 UTC, wakaflorien requested changes

2023-03-29 15:25 UTC, wakaflorien commented on src/controllers/productController.js
>     console.log(req.user);
- remove this console

2023-03-29 15:25 UTC, wakaflorien commented on src/controllers/productController.js
>          error: error.message,
- no need to have error since we are returning 200

2023-03-29 15:25 UTC, wakaflorien commented on src/controllers/resetPasswordController.js
>          status: "fail",
- check this line

2023-03-29 15:25 UTC, wakaflorien commented on src/middlewares/authenticate.js
> +          .json({ status: "error", error: "you are not authorized" });
- you can change error to fail

2023-03-29 17:30 UTC, wakaflorien approved these changes

2023-03-30 07:35 UTC, nicele08 approved these changes

2023-03-30 09:15 UTC, merged