Ft create product
atlp-rwanda/ecommerce-app-champions-bn pull request #29
Opened 2023-03-24 09:10 UTC by Shumba250

#### What does this PR do?

- add the item to the seller's collection
- check if the product exists and returns an appropriate error message
- display an appropriate error message on validation error
- checking product expiry and setting the expiration date of the product
- making the product available 
#### Description of Task to be completed

- an item should be added to the seller's collection and An appropriate response message should be sent to the requesting client upon success/failure of the transaction
- The item should not be duplicated and an appropriate response message containing details of the existing item should be sent to the requesting client suggesting an update of stock levels for the given item.
- When the request body fails any validation checks or the token is not of the role seller and the appropriate 4XX response message should be sent to the requesting client describing the validation error.
#### How should this be manually tested?

- clone the repo
- checkout to ft-create-product branch 
- install the packages by _npm install_
- start the server _npm run dev_
- first login as a vendor i.e you must be having login credentials for the vendor and validated by two-factor-auth
- add a category name on postman through this route /api/category/create
- on postman use this router to add a product  /api/product/create

2023-03-25 13:28 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [A seller should be able to Create/Add a product](https://trello.com/c/n85lNTgy/14-a-seller-should-be-able-to-create-add-a-product)

2023-03-26 11:36 UTC, Shumba250 commented
![](https://github.trello.services/images/mini-trello-icon.png) [A seller should be able to Create/Add a product](https://trello.com/c/n85lNTgy/14-a-seller-should-be-able-to-create-add-a-product)

2023-03-28 20:22 UTC, sostene12 reviewed
hey @Shumba250  you have done a great job
- tests are passing locally
- the creation of product is working

but the Two factor authentication seems not to be working, i had to  comment it in other to run it.

also in the user model, vendor id must be removed in model and migration

2023-03-28 20:22 UTC, sostene12 approved these changes

2023-03-29 07:01 UTC, nicele08 requested changes
Thank your hard work, I left some comments.
Once you've had a chance to work on the feedback, please hit me a message so I can review again and approve the changes.

Keep up the great work!

2023-03-29 07:01 UTC, nicele08 commented on src/api-docs/category.docs.js
> +const category = {
To make the code more readable and easier to understand, I would suggest renaming this variable to something like `postCategory` as it is used on the post request.

2023-03-29 07:01 UTC, nicele08 commented on src/controllers/productController.js
> +          await product.save();
To simplify this code and remove the unnecessary duplicate `await product.save();` call, you can remove the await product.save() line, leaving only the Product.create() call as it will create and save product into the database.

2023-03-29 07:01 UTC, nicele08 commented on src/controllers/productController.js
>            product: { product }
Here is redundant usage of braces around the product object. Remove the braces as they are not necessary and may cause confusion to other developers reading the code.

2023-03-29 07:01 UTC, nicele08 commented on src/controllers/productController.js
> +        .json({ status: "Oops!", message: "only suppliers allowed" });
The status value "Oops!" might not be very clear to users who encounter the error. It might be better to use a more descriptive status message that indicates the reason for the error, such as "Unauthorized Access".

2023-03-29 08:52 UTC, wakaflorien requested changes

2023-03-29 08:52 UTC, wakaflorien commented on src/controllers/productController.js
> +        return res.json({ error: error.message });
- here you forgot to add status to your response. try to be consistent

2023-03-29 08:52 UTC, wakaflorien commented on src/controllers/productController.js
- stay consistent with responses e.g 

`res.status(636).json({status: "success", message: ""})`
`res.status(636).json({status: "fail", error: ""})`

- also correct status code for created is `201`

2023-03-29 08:52 UTC, wakaflorien commented on src/controllers/productController.js
>        return error.message;
- return json response not just error message

2023-03-29 08:52 UTC, wakaflorien commented on src/middlewares/productExists.js
> +        .json({ status: 404, message: "product does not exist" });
- try to not return status code twice here.

2023-03-29 08:52 UTC, wakaflorien commented on src/middlewares/productExists.js
> +    return res.status(500).json({ status: 500, error: "server error" });
- status code in the response is a little bit redudant here too.

try this :
`res.status(500).json({ status: "fail", error: "server error" });`

2023-03-29 08:52 UTC, wakaflorien commented on src/middlewares/productExists.js
> +        .json({ status: 409, message: "product already exists" });
- status code in the response is a little bit redudant here too.

try this :
`res.status(409).json({ status: "fail", message: "product exists" });`

2023-03-29 08:52 UTC, wakaflorien commented on src/middlewares/productExists.js
> +    return res.status(500).json({ status: 500, error: error.message });
- status code in the response is a little bit redudant here too.

try this :
`res.status(500).json({ status: "fail", error: "server error" });`

2023-03-29 15:42 UTC, wakaflorien approved these changes

2023-03-29 15:47 UTC, wakaflorien approved these changes

2023-03-29 15:50 UTC, wakaflorien approved these changes

2023-03-29 15:54 UTC, wakaflorien requested changes

2023-03-29 15:54 UTC, wakaflorien commented on src/controllers/productController.js
> +      return res.status(201).json({ message: "category created", category:postCategory });
- `.json({status: "success",})` can be added.

2023-03-30 08:58 UTC, chrill-christella approved these changes

2023-03-30 09:13 UTC, nicele08 approved these changes

2023-03-30 09:13 UTC, wakaflorien requested changes

2023-03-30 09:13 UTC, wakaflorien commented on src/controllers/productController.js
> +      .json({ message: "category created", category:postCategory });
- missing status in response.

2023-03-30 09:13 UTC, wakaflorien commented on src/controllers/productController.js
>        return error.message;
- return json response .

2023-03-30 09:21 UTC, nicele08 requested changes

2023-03-30 09:21 UTC, nicele08 commented on .env.example
> +api_secret =
it's important to choose names that are clear and descriptive, and that reflect the purpose of each variable. Here are some suggestions for how you could name these variables:
`
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
`
So why did you change them?

2023-03-30 09:21 UTC, nicele08 commented on src/api-docs/category.docs.js
> +const category = {
Same as here I suggest renaming this variable to something like postCategory or you can choose any other clear and descriptive name.

2023-03-30 15:22 UTC, Luciefifi approved these changes

2023-03-30 15:58 UTC, wakaflorien approved these changes

2023-03-30 16:10 UTC, merged