#18 #14 Ft update product
atlp-rwanda/ecommerce-app-champions-bn pull request #32
Opened 2023-03-28 09:05 UTC by Shumba250

#### What does this PR do?

- a seller should update a specific item in a collection
- only the owner of the product is authorized to update a specific item
- a seller can update an existing product
- all inputs are validated 
- appropriate error messages are displayed upon the failure or success of the request
#### Description of Task to be completed

- a seller is authorized to update a product 
- all inputs are validated
- The appropriate 4XX response message is sent to the requesting client describing the validation error
#### How should this be manually tested?

- clone the repo
- navigate to the ft-update-product branch
- install packages by typing npm install
- include Cloudinary variables in .env cloud_name = "" ,  api_key = "", api_secret = ""
- start the server by typing npm run dev
- open your browser to use swagger doc by navigating to localhost/5050/docs
- create vendor a role and permissions
- register a vendor or if you have one created, log the vendor in
- after completing the 2FA authentication, the vendor with be logged in automatically
- on swagger doc, use create product endpoint and only a minimum of 4 images are allowed and create a product
- after creating a product, use update product endpoint and use the product id to update a product

2023-03-28 19:47 UTC, sostene12 approved these changes

2023-03-29 09:54 UTC, wakaflorien requested changes

2023-03-29 09:54 UTC, wakaflorien commented on src/controllers/userController.js
>        return res.status(400).json({ status: "error", error: error.message });
- for consitency and uniformity purposes use something like this on responses instead:

`res.status(400).json({ status: "fail", error: error.message });`

2023-03-29 09:54 UTC, wakaflorien commented on src/controllers/userController.js
>        return res.status(500).json({ status: "error", error: error.message });
- same here

2023-03-29 09:54 UTC, wakaflorien commented on src/middlewares/productExists.js
> +        .json({ status: 404, message: "product does not exist" });
- avoid redudant status codes do something like thsi instead:

`res
        .status(404)
        .json({ status: "fali", message: "product does not exist" });`

2023-03-29 09:54 UTC, wakaflorien commented on src/middlewares/productExists.js
> +    return res.status(500).json({ status: 500, error: "server error" });
### same here

2023-03-29 09:54 UTC, wakaflorien commented on src/middlewares/productExists.js
> +        .status(409)
- ### do the same here

2023-03-29 09:54 UTC, wakaflorien commented on src/middlewares/productExists.js
> +    return res.status(500).json({ status: 500, error: error.message });
- ### again

2023-03-31 07:08 UTC, wakaflorien approved these changes

2023-03-31 07:37 UTC, oliviertech212 approved these changes

2023-03-31 07:46 UTC, chrill-christella approved these changes

2023-03-31 07:51 UTC, merged