Recommended product(a buyer is able to see recommended products)
atlp-rwanda/ecommerce-app-champions-bn pull request #33
Opened 2023-03-29 09:23 UTC by chrill-christella

### what does this PR do?

- implement an endpoint to retrieve recommended products for the buyer

### how should it be manually tested

- clone the repo
- run npm i
- npm run migrate:up
- in postman or thunderclient run  ''http://localhost/3000/api/favproducts"

2023-03-29 09:38 UTC, wakaflorien requested changes

2023-03-29 09:38 UTC, wakaflorien commented on src/middlewares/productExists.js
> +        .json({ status: 404, message: "product does not exist" });
- status codes is redudant here
do something like this instead:
`res.status(404)
        .json({ status: "fail", message: "product does not exist" });`

2023-03-29 09:38 UTC, wakaflorien commented on src/middlewares/productExists.js
> +    return res.status(500).json({ status: 500, error: "server error" });
- same here
`res.status(500).json({ status: "fail", error: "server error" });`

2023-03-29 09:38 UTC, wakaflorien commented on src/middlewares/productExists.js
> +        .json({ status: 409, message: "product already exists" });
- correct this too
`res
        .status(409)
        .json({ status: "fail", message: "product already exists" });`

2023-03-29 09:38 UTC, wakaflorien commented on src/middlewares/productExists.js
> +    return res.status(500).json({ status: 500, error: error.message });
- do the same here

2023-03-29 09:38 UTC, wakaflorien commented on test/product.test.js
- remove this spaces

2023-03-29 11:32 UTC, sostene12 requested changes

2023-03-29 11:32 UTC, sostene12 commented on src/controllers/productController.js
- The product controller is empty, hence you are calling it and which means, the tests are failing aswell, please change that. 
- the tests are failing because that product controller is empty

2023-03-29 12:28 UTC, patsicko approved these changes

2023-03-30 15:46 UTC, sostene12 approved these changes

2023-03-30 15:50 UTC, Luciefifi approved these changes

2023-03-30 15:56 UTC, sostene12 commented on src/controllers/productController.js
remove those console logs

2023-03-30 15:56 UTC, sostene12 commented on .env.example
- may be you can change those variables from small letters to capital letters

2023-03-31 09:50 UTC, chrill-christella commented on .env.example
I did change it... thanks

2023-03-31 12:03 UTC, sostene12 reviewed
- can you make , the meaningful PR, which have all details and event for testing the endpoints also solve the conflicts

2023-03-31 12:03 UTC, sostene12 commented on .env.example
- i think the env vars are wrong, when you rebase you will see , they are "CLOUDINARY_NAME" like that

2023-03-31 12:16 UTC, wakaflorien requested changes

2023-03-31 12:16 UTC, wakaflorien commented on src/controllers/productController.js
>          return res
- return complete json response

2023-03-31 12:16 UTC, wakaflorien commented on src/controllers/productController.js
>            .status(404)
- return a complete json response

2023-03-31 12:33 UTC, wakaflorien approved these changes

2023-03-31 12:34 UTC, merged