#54 Create REST APIs for a buyer to create product review
atlp-rwanda/ecommerce-app-champions-bn pull request #38
Opened 2023-04-03 21:27 UTC by patsicko

# What this PR do
## Create product review
## Get product rating
## Update product review
## Delete Product review

# Description of the task
- Create POST request for a buyer to create a review
- Create a PATCH api to update review
- Create a GET request for getting product review and rating
- Create a DELETE request to deletea review
- Create a swagger documentation [Delivers #54]
## How should this be manually tested
- clone the repo
- use npm install to install all packages
- Add all required environment variables following the .env.example provided
- use npx sequelize db:migrate to migrate migrations
- Run npm run db:seeds to populate seeders in database
- use npm run dev to start the server
- Navigate to  the http://localhost:PORT/docs on your browser to access swagger APIs docs  by replacing 'PORT' with the port that your the app is listening to. 
- Create a product review
- Sign up as a buyer, and login to have vendor's permissions
- Tryout  POST//api/review/createReview, GET//api/review/getProductRate/1
- A list of product reviews will be displayed as a response

2023-04-04 08:09 UTC, sostene12 approved these changes

2023-04-04 08:24 UTC, patsicko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Buyer should be able to provide a review](https://trello.com/c/M0kqKRBu/54-buyer-should-be-able-to-provide-a-review)

2023-04-04 13:33 UTC, wakaflorien requested changes

2023-04-04 13:33 UTC, wakaflorien commented on src/controllers/reviewController.js
> +    res.json({
- good job on reviews and rating overall but on this response try to return meaningful and correct response as you did in above lines.

2023-04-05 16:13 UTC, Shumba250 approved these changes

2023-04-05 18:50 UTC, wakaflorien approved these changes

2023-04-05 19:40 UTC, merged