#27clearing buyer's Cart
atlp-rwanda/ecommerce-app-champions-bn pull request #39
Opened 2023-04-04 08:37 UTC by oliviertech212

#### What does this PR do?

- clearing buyer's cart
- reset cart total to zero
- document endpoint with swagger
- add translation
#### Description 
handle the clearing of the buyer's cart, including emptying the cart and resetting the cart total to zero.
#### How should this be manually tested?
- clone the repo `git clone https://github.com/atlp-rwanda/ecommerce-app-champions-bn.git`
- checkout to `ft-clearCart`
- install the packages by `npm install`
- run migrations and seeds 
- start the server `npm run dev`
- open your browser and type ` http://localhost:{PORT}/docs`
-  first  you have to login as a buyer i.e you must be having login credentials for the  buyer
- add product to cart 
- look into your database cart table and then copy the cart id
- paste cartid. into id field in your swagger Ui endpoint 
### Trello cardNumber#27

2023-04-04 08:59 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Buyer should be able to clear their cart](https://trello.com/c/RZznarQT/27-buyer-should-be-able-to-clear-their-cart)

2023-04-04 10:19 UTC, nicele08 requested changes
@oliviertech212 Great job, however I did notice areas for improvement so work on them then we move forward.

2023-04-04 10:19 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +    }
It's good practice to declare responses in a separate file when working with Swagger documentation. This can make it easier to manage the documentation and keep it organized, especially when there are multiple endpoints and response codes to document.
Example:
```javascript
export const responses = {
      200: {
        description: "Success"
      },
      400: {
        description: "Bad request"
      },
      401: {
        description: "Unauthorized"
      },
      500: {
        description: "internal server error"
      }
    }
``` 
Then you'll use `responses` wherever you want instead of duplicating them.

2023-04-04 10:19 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +    }
Same as here, after defining responses in separate file, you can use it here.

2023-04-04 10:19 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +    "/api/cart/clearCart/{id}":{
It's better to follow endpoint naming conventions typically follow the style of the URI path, where each segment is separated by a hyphen or underscore to make it more readable and understandable. This convention makes it easier for developers to read and understand the endpoints and their associated functionality.
Example:
```javascript
/api/users/create-new-user
/api/users/update-user-info
/api/users/get-user-profile
``` 
Using hyphens to separate words in the endpoint names makes them more readable and understandable, especially when there are multiple words involved.

While using camelCase for endpoint names may not be technically incorrect, it could cause confusion for developers who are not familiar with the naming convention. It's important to follow the established conventions for endpoint naming to ensure that your API is consistent, readable, and easy to use.

2023-04-04 10:19 UTC, nicele08 commented on src/api-docs/product.docs.js
> +         "/api/product/seller/getall":{get: listProduct},
The endpoint naming convention in the example you provided is not following the best practice of using hyphens or underscores to separate words in endpoint names.

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/cartController.js
> +            quantity: 1,
Please you need to improve this. I think you have to allow the user to specify the quantity of the product they want to add to the cart, but defaults to 1 if no quantity is specified.
Remember to check to see if the quantity of the product being added is greater than the available quantity in the stock. If it is, I return a 400 status code and an appropriate error message.

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/cartController.js
> +      const Cart = await cart.findOne({ where:{ buyerId:req.user.id } });
As a best practice, I recommend using `camelCase` for variable and function names in our codebase. This naming convention helps make the code more consistent, readable, and easier to understand. However, we do allow class names to use PascalCase, as this is a common convention for naming classes in many programming languages.
For example, instead of using `Cart` for a variable name, I suggest using `cart`. This makes the code more consistent with the naming convention used in the rest of the codebase.

If you are defining a class, it is acceptable to use PascalCase for the class name. For example, you can define a class called `CartItem` instead of `cartItem`. This helps to differentiate classes from variables and functions and makes the code more readable.

Please keep this naming convention in mind when writing code.

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/cartController.js
> +          .reduce((sum, next) => sum + next);
Is the `productTotal` in JSON format? If the `productTotal ` values in the Cart.products array are already numeric and not in JSON format, there is no need to use JSON.parse() to convert them to numbers in the second code snippet. Therefore, it would be best to remove the JSON.parse() function.

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/cartController.js
> +      const Cart = await cart.findOne({ where: { buyerId: req.user.id,id:req.params.id } });
Same as here use `camelCase`

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/productController.js
> +      const product = await Product.findAll({ where: {VendorId:vendor.id } });
`findAll` returns array so the good name could be `products` as we may have many products.

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/productController.js
> +      }
Unnecessary check: The code checks whether product is null or not, but since the findAll function always returns an array, this check is unnecessary. Instead, the code should check whether product.length is 0 to see if there are no products.

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/productController.js
> +      return res.status(200).json({ status: req.t("success"),products:{product} });
Returning an unnecessary object: The code is returning the product array wrapped in an unnecessary object. It would be better to simply return the array itself.
Example: 
```javascript
return res.status(200).json({ status: req.t("success"),products: products });
```

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/productController.js
> +    }
It would be better to include the error message in the response, so that clients can see what went wrong.
hint:
```javascript
res.status(500).json({ status: "error", message: error.message });
```

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/productController.js
> +          }
Nested conditional logic: The productsToUpdate query uses nested conditional logic with the [Op.and] and [Op.or] operators, which can make the code harder to read and understand. It might be better to split the query into multiple simpler queries to make it more readable.

Hint: 
```javascript
where: {
        productId: searchParam,
        quantity: 0,
        expired: true,
        VendorId: vendor.id
      }
```

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/productController.js
> +      );
this `Product.update()` statement updates the available field for products based on their productId, but it is not clear what this field represents. It would be better to include a comment explaining what the field does and why it needs to be updated.

2023-04-04 10:19 UTC, nicele08 commented on src/controllers/productController.js
> +          }
Same as here: Nested conditional logic: The productsToUpdate query uses nested conditional logic with the [Op.and] and [Op.or] operators, which can make the code harder to read and understand. It might be better to split the query into multiple simpler queries to make it more readable.

Hint: 
```javascript
where: {
        productId: searchParam,
        quantity: 0,
        expired: true,
        VendorId: vendor.id
      }
```

2023-04-04 10:19 UTC, nicele08 commented on src/routes/cart.route.js
> +cartRoute.delete("/clearCart/:id",verifyBuyer,CartController.clearCart );
Use hyphens to separate words in the endpoint names makes them more readable and understandable, especially when there are multiple words involved.

2023-04-04 10:19 UTC, nicele08 commented on src/routes/product.route.js
> +productRoute.get("/seller/getall",verifyVendor,ProductController.availableProductsInCollection);
Same as here; Use hyphens to separate words in the endpoint names makes them more readable and understandable, especially when there are multiple words involved.

2023-04-04 14:12 UTC, wakaflorien commented on src/controllers/productController.js
> +      console.log(error.message);
- remove console logs after you have tested your codes.

2023-04-04 14:20 UTC, wakaflorien requested changes
- Good job on clear. improve on PR description make sure it contains step by step to testing this endpoint.  <details><summary>Details</summary>
<p>

- does not tell what endpoint you have to use

</p>
</details>

2023-04-04 14:20 UTC, wakaflorien commented on test/buyer.test.js
>    });
- i see no tests for clear cart

2023-04-05 07:56 UTC, Shumba250 approved these changes

2023-04-05 09:00 UTC, sostene12 requested changes

2023-04-05 09:00 UTC, sostene12 commented on src/controllers/cartController.js
- clearing the cart is not working, I see the message that it have cleared successfully but i see the cart still have the contents.

2023-04-05 10:48 UTC, nicele08 requested changes

2023-04-05 10:48 UTC, nicele08 commented on src/api-docs/response.js
> +  };
Here it would be more appropriate to use actual HTTP status codes rather than custom keys like success, badRequest, etc.

Hint: 
```javascript
200: {
      description: "Success"
    },
    400: {
      description: "Bad request"
    },

// ... continue with rest of other status code
```

2023-04-05 10:48 UTC, nicele08 commented on src/api-docs/response.js
> +  module.exports = responses;
I would suggest using ES6 syntax for exporting the object.

Hint: 
```javascript
export default objectName
```

2023-04-05 10:48 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +    }
I left comment on the responses file. If you fix it properly we'll only have one line here 😁 like `responses: responses` for just `responses`

2023-04-05 10:48 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +    }
Same as here. Let's have this in just one line.

2023-04-05 10:48 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +        example: "1"
If type is `integer` why are you putting the value inside quotation?

2023-04-05 15:51 UTC, wakaflorien reviewed
- Rebase to solve conflicts.

2023-04-05 19:42 UTC, wakaflorien reviewed
- solve new conflicts and push again

2023-04-05 20:10 UTC, nicele08 requested changes
@oliviertech212 good progress, just check new comments.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/response.js
> +  const  Responses={
I would suggest updating the variable name `Responses` to `responses` to follow the camelCase naming convention.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/response.js
> +    }
This is good. ✔

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +import Responses from "./response";
I would suggest updating the imported module name `Responses` to `responses` to follow the camelCase naming convention.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +  responses:Responses
if you rename import to `responses` here you can just type `responses,`

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +  responses: Responses
same as here, if you rename import to responses here you can just type `responses,`. The shorthand property syntax to simplify the object literal notation when creating an object with a property name that matches a variable name.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +    responses: Responses
Same as here, update and use camelCase to import `responses` to shorthand property syntax to simplify the object literal notation when creating an object with a property name that matches a variable name.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/cart.docs.js
> +    responses:Responses
Same as here, update and use camelCase to import `responses` to shorthand property syntax to simplify the object literal notation when creating an object with a property name that matches a variable name.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/product.docs.js
> +            }
As you did on `clearCart`, I would suggest using the declared responses object to simplify the code and reduce duplication. If you do that, we'll only have one line here.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/product.docs.js
> +      }
Same as here; As you did on `clearCart`, I would suggest using the declared responses object to simplify the code and reduce duplication. If you do that, we'll only have one line here.

2023-04-05 20:10 UTC, nicele08 commented on src/api-docs/product.docs.js
> +            }
Same as here; As you did on `clearCart`, I would suggest using the declared responses object to simplify the code and reduce duplication. If you do that, we'll only have one line here.

2023-04-06 05:33 UTC, nicele08 approved these changes
@oliviertech212 you did great.🎉

2023-04-06 05:41 UTC, wakaflorien approved these changes

2023-04-06 19:54 UTC, sostene12 approved these changes

2023-04-07 10:10 UTC, merged