ch(setting up environment):
atlp-rwanda/ecommerce-app-champions-bn pull request #4
Opened 2023-03-02 16:42 UTC by Luciefifi

# What does this PR do 
This pull request adds the necessary environments variables to set up the development and production environments for the application

# Description of the task to be completed
- create a '.env' file in the root directory of the project
- Define and add the necessary environments variables
- Add the '.env' file in '.gitignore' file. to prevent sensitive information from being pushed to repository
- create '.env.example' file in root directory and add only the variables

# How should this be manually tested 
- clone the repository 
- install dependencies by 'npm install'
- create '.env' file to add all environments variables by referring to '.env.example' file 
- then follow what readme file says

# relevant pivotal tracker story
#15

2023-03-02 17:14 UTC, wakaflorien requested changes
- add trello card in your description with checked or unchecked sub tasks.
- use the correct card number for **PR** title, descrition and commits.
- **PRODUCTION_DATAB**  does not make sense.
- check your card again see if everything is checked

2023-03-02 17:57 UTC, sostene12 requested changes
-please configure the environment effectively, for production, testing, and development
-create a config file that will manage that

2023-03-03 02:34 UTC, oliviertech212 reviewed
use an assignment operator for each and every variable for consistency

and  you can add PRO_DATABASE_URL=postgres://username:password@host/
database   
for  those who will decide to use URL look at  config/config.js and model/index.js
![Screenshot from 2023-03-03 04-23-40](https://user-images.githubusercontent.com/89464364/222615794-e87d8014-9965-4d36-b55f-841dbf81370b.png)   
![Screenshot from 2023-03-03 04-07-05](https://user-images.githubusercontent.com/89464364/222615857-5d7d57a9-d5ff-4b9b-b8a7-bf18680ef2c8.png)

2023-03-06 08:19 UTC, patsicko approved these changes

2023-03-06 09:13 UTC, oliviertech212 approved these changes

2023-03-06 11:40 UTC, wakaflorien approved these changes

2023-03-06 14:59 UTC, merged