ft(view-cart) buyer should be able to view items in the cart
atlp-rwanda/ecommerce-app-champions-bn pull request #40
Opened 2023-04-04 11:40 UTC by chrill-christella

### what does this PR do?

 implement the GET endpoint for the buyer to view items in cart

### How should it be manually tested

• clone the repo using git clone repository's URL
• change branch git checkout ft-view-cart
• run npm install, npm run migrate:up and npm run db:seeds
• run the endpoint within the swagger or send get request http://localhost:<PORT>/api/cart/getAll

### What are the relevant pivotal tracker stories?

https://trello.com/c/99dTN28l

2023-04-04 14:43 UTC, wakaflorien commented on src/controllers/cartController.js
> +        res.status(304).json({ status:"success", Cart });
- return correct response

```suggestion
        res.status(200).json({ status:"success", message: "cart items", data:Cart });
```

2023-04-04 14:45 UTC, wakaflorien requested changes

2023-04-04 14:45 UTC, wakaflorien commented on test/buyer.test.js
> +  })
- write more tests for different scenarios that may happen when performing this action.

2023-04-05 06:31 UTC, Shumba250 approved these changes

2023-04-05 09:23 UTC, sostene12 requested changes
- get the user cart is showing empty

2023-04-05 16:07 UTC, wakaflorien commented on src/controllers/cartController.js
> +      const Cart = await cart.findOne({ where: { buyerId: req.user.id } });
- this will return all available carts for the specific user. what if we want single cart with it's items?

2023-04-06 11:26 UTC, wakaflorien approved these changes

2023-04-06 11:54 UTC, sostene12 approved these changes

2023-04-06 11:59 UTC, wakaflorien approved these changes

2023-04-06 11:59 UTC, merged