#44 Email and in-app notifications
atlp-rwanda/ecommerce-app-champions-bn pull request #44
Opened 2023-04-06 09:22 UTC by patsicko

# What this PR do
- Create email and in-app notifications
## Description of the  task to be completed

- To send email notifications  to the product lifecycle changes
- To send app notifications to the product lifecycle changes 

## How should this be manually tested?

- git clone from repo
- switch into branch
- run npm i
- ## How should this be manually tested
- clone the repo
- use npm install to install all packages
- Add all required environment variables following the .env.example provided
- use npx sequelize db:migrate to migrate migrations
- Run npm run db:seeds to populate seeders in database
- use npm run dev to start the server
- Navigate to  the http://localhost:PORT/docs on your browser to access swagger APIs docs  by replacing 'PORT' with the port that your the app is listening to. 
- run npm run dev
- try to add product
- check your email  and app for notification:
- Trello ID: #44

2023-04-06 10:34 UTC, patsicko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications](https://trello.com/c/PFoM0IkO/44-notifications)

2023-04-11 18:45 UTC, wakaflorien requested changes

2023-04-11 18:45 UTC, wakaflorien commented on src/controllers/notificationController.js
> +  const sendEmaiOption = {
- change the variable name to make it readable and self-explanatory

2023-04-11 18:45 UTC, wakaflorien commented on src/controllers/notificationController.js
> +    const sendEmaiOption = {
- same here, variable naming is crucial

2023-04-12 07:17 UTC, oliviertech212 approved these changes

2023-04-12 08:17 UTC, chrill-christella approved these changes

2023-04-12 10:25 UTC, Luciefifi approved these changes

2023-04-12 10:51 UTC, sostene12 requested changes

2023-04-12 10:51 UTC, sostene12 commented on src/controllers/notificationController.js
you've done a great job @patsicko , you can also make it better by adding more details
- organize the email details in the email templates
- add other endpoints for getting the notifications

2023-04-13 07:39 UTC, wakaflorien approved these changes

2023-04-13 13:52 UTC, sostene12 approved these changes

2023-04-13 13:57 UTC, merged