A RESTful API for buyer payments
atlp-rwanda/ecommerce-app-champions-bn pull request #48
Opened 2023-04-10 14:05 UTC by Shumba250

#### What does this PR do?

- Create an endpoint for processing buyer payments
- Update order status
- sending confirmation to the frontend
- swagger documentation of the payment endpoint
#### Description of Task to be completed

- The payment is processed via Stripe API
- The order status is updated to reflect the payment
- The Sales table is created to reflect the payment
- A receipt is sent to the buyer upon the success of the payment
- the quantity of the product sold are removed and the products quantity is updated with unsold products quantity
- appropriate error messages are displayed on the failure of the transaction
#### How should this be manually tested?

- clone the repo
- switch to _ft-buyer-payment_ branch
- type npm install to install all packages
- _npm run migrate:up_ and _npm npm run db:seeds_ 
- run the server by typing _npm run dev_
- in your browser navigate to swagger doc by typing localhost:PORT/docs/
- first add a product to cart
- you either choose to update the cart by changing the quantity of the product
- after you can checkout by navigating to the checkout endpoint
- copy the URL provided and past it in the browser to process the payment
- when the payment is successful, a receipt is send to the buyer via email.

2023-04-11 07:31 UTC, wakaflorien commented on src/controllers/paymentController.js
> +        const amount = element.productPrice * 100;
- is there any specific reason for multiplying with 100

2023-04-11 11:41 UTC, Shumba250 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Buyer should be able to make a payment](https://trello.com/c/AogRpYcN/50-buyer-should-be-able-to-make-a-payment)

2023-04-11 15:13 UTC, patsicko approved these changes

2023-04-11 18:23 UTC, wakaflorien reviewed
![image](https://user-images.githubusercontent.com/48131185/231254949-648d6219-83d5-46da-84d3-49e532c9fc76.png)
Can you improve on tests

2023-04-12 09:15 UTC, Luciefifi approved these changes

2023-04-12 09:55 UTC, sostene12 requested changes

2023-04-12 09:55 UTC, sostene12 commented on src/controllers/paymentController.js
you have done the great work @Shumba250 , and it will be perfect if you add some of the following,
- the endpoints of getting the orders for the customer are necessary
- also the endpoints for getting the sales and may be adding the statistics if possible

2023-04-12 10:58 UTC, chrill-christella approved these changes

2023-04-13 13:57 UTC, merged