setup support languages:
atlp-rwanda/ecommerce-app-champions-bn pull request #5
Opened 2023-03-02 18:28 UTC by chrill-christella

### what does this PR do?

setting up support language for the project

### Description of the task to be completed

 this PR includes the following changes to the project:

- installation of  i18next library, backend and middleware dependencies
- creation of  folder for languages which includes english as default, french and kinyarwanda (json files)
- configuration of this languages in a new file named as language.js

### how should it be manually tested

- clone the repository on github
- install depedencies by "npm install"
- run npm run dev
- then test the endpoint  by "http://localhost:3000/"
- go to headers  and accept languages(fr, kin) 

### relevant pivot tracker story

#12

2023-03-02 18:45 UTC, wakaflorien requested changes
- make sure **.env** file is ignored.
- make sure **.DS_store** is ignored too.
- add related card number in your **PR** description.
- add label reflecting your status of your work.

2023-03-03 11:45 UTC, wakaflorien approved these changes

2023-03-03 14:01 UTC, Shumba250 approved these changes

2023-03-06 07:56 UTC, oliviertech212 approved these changes

2023-03-06 11:38 UTC, merged