ch(setup-dockerfile)
atlp-rwanda/ecommerce-app-champions-bn pull request #6
Opened 2023-03-02 19:24 UTC by phanuelnd

**-What does this PR do?**

-Creation of Docker configfile for the backend

**Descrption of the task completed**:

-Creation of configuration file for the backend
-Pushing of the backend image to the docker hub

**How should this be tested?**

-Download Docker for the desktop
-Pull the image with this link docker pull atlpchamps/ecommerce -Install docker in VS Code or other code editor of your choice Finishes01

2023-03-06 12:52 UTC, wakaflorien commented on docker-compose.yml
> +      - POSTGRES_DB=${DB_NAME}
Getting some credentials issue

2023-03-06 12:55 UTC, wakaflorien requested changes
- can we add run script in package.json

2023-03-06 13:23 UTC, sostene12 commented
> * can we add run script in package.json

let me change it

2023-03-06 14:02 UTC, sostene12 commented
> > * can we add run script in package.json
> 
> let me change it

done it

2023-03-06 14:41 UTC, wakaflorien commented on docker-compose.yml
> +      - POSTGRES_USER=${DB_USERNAME}
- can we add ports?
- included needed env variables in README.md file

2023-03-09 13:04 UTC, wakaflorien approved these changes

2023-03-09 13:04 UTC, merged